name: salons_app_flutter_module
description: A new Flutter module.

#  flutter packages pub run build_runner build --delete-conflicting-outputs


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.0.4
  hive_generator: ^1.1.0
  hive_flutter: ^1.0.0

  #----- Firebase ------
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_storage: ^9.0.0

  #----- Backend ------
  retrofit: ^2.0.1
  logger: ^1.0.0
  dio: ^4.0.0
  json_annotation: ^4.0.0

  #----- Social login ------
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.4.0

  #----- Shared preferences ----
  shared_preferences: ^2.0.6

  universal_html: ^2.0.8

  # Functional programming thingies
  dartz: ^0.10.0-nullsafety.2

  #---- DateTime Formatter ----
  #  intl: 0.16.0

  #----- Checking internet connection -----
  #  data_connection_checker: ^0.3.4

  #----- Reactive ----
  #  rxdart: ^0.22.3

  #------ For Intents ------
  #  url_launcher: ^5.1.4

  #---- Dependency Injection -----
  get_it: ^7.1.3

  #generate id
  uuid: 3.0.4

  flutter_svg: ^0.22.0

  #------ Toast message ------
  fluttertoast: ^8.0.7

  #------ Image picker ------
  #  image_picker: 0.6.7+2
  image_picker_web: 2.0.1

  #------ UI -------
  font_awesome_flutter: ^9.0.0
  cached_network_image: ^3.0.0
  #  flutter_speed_dial: ^1.0.4
  #  loading: ^1.0.1

  tuple: ^2.0.0

  #-------- JSON Annotations -----
  #  json_annotation: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

    #----- REST APIs ------
  #  chopper_generator: ^2.3.4

  #------ For Serialization objects ------
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  retrofit_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.salons_app_flutter_module
    iosBundleIdentifier: com.example.salonsAppFlutterModule
